apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: python-api-grafana
spec:
  service:
    type: LoadBalancer
  ingress:
    enabled: False
  config:
    log:
      mode: "console"
      level: "warn"
    security:
      admin_user: "admin"
      admin_password: "GRAFANA-PASSWORD"
    auth.anonymous:
      enabled: True
  dashboardLabelSelector:
    - matchExpressions:
        - { key: app, operator: In, values: [go-api] }