apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  labels:
    name: prometheus
spec:
  selector:
    matchLabels:
      operated-prometheus: "true"
  namespaceSelector:
    any: true
  endpoints:
    - port: web
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel
  labels:
    name: otel
spec:
  selector:
    matchLabels:
      app: otel-python-api
  namespaceSelector:
    any: true
  endpoints:
    - port: monitoring
      targetPort: 8888
      path: '/metrics'
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: go-api
  labels:
    name: go-api
spec:
  selector:
    matchLabels:
      app: go-api
  namespaceSelector:
    any: true
  endpoints:
    - port: api
      targetPort: 8080
      path: '/metrics'