apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-api
spec:
  selector:
    matchLabels:
      app: dotnet-api
  template:
    metadata:
      labels:
        app: dotnet-api
      annotations:
        # sidecar.opentelemetry.io/inject: "true"
        instrumentation.opentelemetry.io/inject-dotnet: "true"
    spec:
      containers:
      - name: dotnet-api
        image: dotnet-api
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
