apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
  labels:
    app: go-api
spec:
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
      - name: go-api
        image: go-api
        resources:
          requests:
            memory: 32Mi
            cpu: 10m
          limits:
            memory: "64Mi"
            cpu: "50m"
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        # livenessProbe:
        #   httpGet:
        #     path: /api/v1/healthz
        #     port: 8080
        #   initialDelaySeconds: 10
        #   periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: go-api
  labels:
    app: go-api
spec:
  selector:
    app: go-api
  ports:
  - name: api
    port: 8080
    targetPort: 8080